function set_planet_names() {
	global.planet_names[0] = "Pubbaogawa"
	global.planet_names[1] = "Enriostea"
	global.planet_names[2] = "Kengypso"
	global.planet_names[3] = "Kezilles"
	global.planet_names[4] = "Gopra"
	global.planet_names[5] = "Onus"
	global.planet_names[6] = "Cepapra"
	global.planet_names[7] = "Phihigawa"
	global.planet_names[8] = "Morix 94XK"
	global.planet_names[9] = "Sippe 3JID"
	global.planet_names[10] = "Yodeithea"
	global.planet_names[11] = "Henzapra"
	global.planet_names[12] = "Cholrypso"
	global.planet_names[13] = "Nondagua"
	global.planet_names[14] = "Castea"
	global.planet_names[15] = "Xeotania"
	global.planet_names[16] = "Crigupra"
	global.planet_names[17] = "Llovagantu"
	global.planet_names[18] = "Crao 8"
	global.planet_names[19] = "Diri 4XO"
	global.planet_names[20] = "Llinda M1X2"
	global.planet_names[21] = "Zars 456"
	global.planet_names[22] = "Lenkaenus"
	global.planet_names[23] = "Goccanides"
	global.planet_names[24] = "Chonzolla"
	global.planet_names[25] = "Xunzars"
	global.planet_names[26] = "Thovis"
	global.planet_names[27] = "Gulara"
	global.planet_names[28] = "Phadinia"
	global.planet_names[29] = "Thonanides"
	global.planet_names[30] = "Vadus 19NP"
	global.planet_names[31] = "Lides 3CJ"


}
