if x < camera_get_view_border_x(view_camera[1])
	x = camera_get_view_border_x(view_camera[1])
if y < camera_get_view_border_y(view_camera[1])
	y = camera_get_view_border_y(view_camera[1])
if x > room_width-camera_get_view_border_x(view_camera[1])
	x = room_width-camera_get_view_border_x(view_camera[1])
if y > room_height-camera_get_view_border_y(view_camera[1])
	y = room_height-camera_get_view_border_y(view_camera[1])